package com.edgedeploy.worker.docker;

import com.edgedeploy.worker.framework.DetectedProject;
import com.edgedeploy.worker.framework.Framework;
import org.springframework.stereotype.Component;

/**
 * Next.js server.
 *
 * <pre>
 * build:   node image -> install -> next build -> drop devDependencies
 * runtime: node image, non-root user, next start
 * </pre>
 * Works without requiring {@code output: "standalone"} in the user's next.config; adopting standalone
 * output later would shrink the image further.
 */
@Component
class NextJsBuildStrategy implements BuildStrategy {


    @Override
    public Framework framework() {
        return Framework.NEXTJS;
    }

    @Override
    public int port(BuildSettings settings) {
        return settings.appPort();
    }

    @Override
    public String dockerfile(BuildSettings settings) throws BuildConfigurationException {
        DetectedProject project = settings.project();
        DockerfileWriter.requireCommand(settings.buildCommand(), "Build command");
        DockerfileWriter.requireCommand(settings.startCommand(), "Start command");
        String build = settings.buildCommand() != null ? settings.buildCommand()
                : project.hasScript("build") ? project.packageManager().runScript("build") : "node_modules/.bin/next build";
        String start = settings.startCommand() != null ? settings.startCommand()
                : "node_modules/.bin/next start --hostname 0.0.0.0 --port " + settings.appPort();

        DockerfileWriter dockerfile = new DockerfileWriter()
                .comment("Generated by EdgeDeploy for NEXTJS (" + project.packageManager() + "). Not part of your repository.")
                .from(settings.nodeImage(), "build")
                .raw("WORKDIR /app")
                .raw("ENV CI=true NEXT_TELEMETRY_DISABLED=1");
        DockerfileWriter.installDependencies(dockerfile, project)
                .raw("COPY . .")
                .run(build);
        if (project.packageManager().pruneCommand() != null) {
            dockerfile.run(project.packageManager().pruneCommand());
        }
        return dockerfile
                .blank()
                .from(settings.nodeImage(), "runtime")
                .raw("WORKDIR /app")
                .raw("ENV NODE_ENV=production NEXT_TELEMETRY_DISABLED=1 PORT=" + settings.appPort())
                .raw("COPY --from=build --chown=node:node /app ./")
                .raw("USER node")
                .raw("EXPOSE " + settings.appPort())
                .cmd(start)
                .toString();
    }
}
