package com.edgedeploy.worker.docker;

import com.edgedeploy.worker.framework.DetectedProject;
import com.edgedeploy.worker.framework.Framework;
import org.springframework.stereotype.Component;

import java.util.regex.Pattern;

/**
 * Node.js server.
 *
 * <pre>
 * build:   node image -> install -> optional build script (e.g. TypeScript) -> drop devDependencies
 * runtime: node image, non-root user, npm start (or node {main})
 * </pre>
 */
@Component
class NodeBuildStrategy implements BuildStrategy {

    private static final Pattern MAIN = Pattern.compile("^(?!/)(?!.*\\.\\.)[A-Za-z0-9._/-]{1,200}$");

    @Override
    public Framework framework() {
        return Framework.NODE;
    }

    @Override
    public int port(BuildSettings settings) {
        return settings.appPort();
    }

    @Override
    public String dockerfile(BuildSettings settings) throws BuildConfigurationException {
        DetectedProject project = settings.project();
        DockerfileWriter.requireCommand(settings.buildCommand(), "Build command");
        DockerfileWriter.requireCommand(settings.startCommand(), "Start command");

        String start;
        if (settings.startCommand() != null) {
            start = settings.startCommand();
        } else if (project.hasScript("start")) {
            // npm is always present in the runtime image and simply runs the "start" script.
            start = "npm start";
        } else if (project.main() != null && MAIN.matcher(project.main()).matches()) {
            start = "node " + project.main();
        } else {
            throw new BuildConfigurationException("Cannot tell how to start this Node.js app: add a \"start\" script "
                    + "to package.json or set a start command in project settings");
        }
        String build = settings.buildCommand() != null ? settings.buildCommand()
                : project.hasScript("build") ? project.packageManager().runScript("build") : null;

        DockerfileWriter dockerfile = new DockerfileWriter()
                .comment("Generated by EdgeDeploy for NODE (" + project.packageManager() + "). Not part of your repository.")
                .from(settings.nodeImage(), "build")
                .raw("WORKDIR /app")
                .raw("ENV CI=true");
        DockerfileWriter.installDependencies(dockerfile, project).raw("COPY . .");
        if (build != null) {
            dockerfile.run(build);
        }
        if (project.packageManager().pruneCommand() != null) {
            dockerfile.run(project.packageManager().pruneCommand());
        }
        return dockerfile
                .blank()
                .from(settings.nodeImage(), "runtime")
                .raw("WORKDIR /app")
                .raw("ENV NODE_ENV=production PORT=" + settings.appPort())
                .raw("COPY --from=build --chown=node:node /app ./")
                .raw("USER node")
                .raw("EXPOSE " + settings.appPort())
                .cmd(start)
                .toString();
    }
}
