package com.edgedeploy.worker.docker;

import com.edgedeploy.worker.framework.DetectedProject;

/**
 * Single-page apps that compile to static files (Vite, Create React App).
 *
 * <pre>
 * build:   node image -> install dependencies -> run the build script
 * runtime: unprivileged nginx serving the output, with SPA fallback to index.html
 * </pre>
 * The runtime image contains only the compiled assets: no Node.js, no source, no node_modules.
 */
abstract class StaticSiteBuildStrategy implements BuildStrategy {

    static final int PORT = 8080;

    /** Where the framework writes its production build. */
    abstract String outputDirectory();

    /** Static sites are served by nginx on a fixed port, independent of the app port. */
    @Override
    public int port(BuildSettings settings) {
        return PORT;
    }

    @Override
    public String dockerfile(BuildSettings settings) throws BuildConfigurationException {
        DetectedProject project = settings.project();
        String build = settings.buildCommand();
        DockerfileWriter.requireCommand(build, "Build command");
        if (build == null) {
            if (!project.hasScript("build")) {
                throw new BuildConfigurationException("package.json has no \"build\" script; add one or set a build "
                        + "command in project settings");
            }
            build = project.packageManager().runScript("build");
        }

        DockerfileWriter dockerfile = new DockerfileWriter()
                .comment("Generated by EdgeDeploy for " + framework() + " (" + project.packageManager() + "). Not part of your repository.")
                .from(settings.nodeImage(), "build")
                .raw("WORKDIR /app")
                .raw("ENV CI=true");
        DockerfileWriter.installDependencies(dockerfile, project)
                .raw("COPY . .")
                .run(build)
                .blank()
                .from(settings.staticRuntimeImage(), "runtime")
                .raw("COPY --from=build /app/" + outputDirectory() + " /usr/share/nginx/html")
                // nginx config inline (heredoc): no extra files in the user's build context.
                .raw("COPY <<'NGINX' /etc/nginx/conf.d/default.conf")
                .raw("server {")
                .raw("    listen " + PORT + ";")
                .raw("    root /usr/share/nginx/html;")
                .raw("    location / {")
                .raw("        try_files $uri $uri/ /index.html;")
                .raw("    }")
                .raw("}")
                .raw("NGINX")
                .raw("EXPOSE " + PORT);
        return dockerfile.toString();
    }
}
